name: Docker Image CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker version
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          # 使用Dockerfile构建镜像
          docker build . --file dockerfile.node.18.9.0 --tag  ${{ secrets.DOCKER_USERNAME }}/node:18.9.0
          # 推送镜像到镜像仓库
          docker push ${{ secrets.DOCKER_USERNAME }}/node:18.9.0
